const {test} = require('node:test');
const assert = require('node:assert/strict');
const {spawn} = require('node:child_process');
const path = require('node:path');
const {once} = require('node:events');
const {chromium, devices} = require('playwright');

test('iPhone-sized PWA: range, rules, reversible stats, custom routes, persistence and offline launch', {timeout:60000}, async()=>{
 const root=path.resolve(__dirname,'..');
 const server=spawn('python3',['-u','-m','http.server','0','--bind','127.0.0.1','--directory',path.dirname(root)],{stdio:['ignore','pipe','ignore']});
 let browser;
 try{
  const [line]=await once(server.stdout,'data');
  const port=String(line).match(/port (\d+)/)[1];
  const base=`http://127.0.0.1:${port}/${path.basename(root)}/`;
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',args:['--no-sandbox']});
  const context=await browser.newContext({...devices['iPhone 13'],defaultBrowserType:undefined});
  let page=await context.newPage();
  const errors=[]; const failed=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400 && !r.url().endsWith('/favicon.ico')) failed.push(r.url());});
  const ready=async()=>page.waitForFunction(()=>document.getElementById('currentScore').textContent!=='--');
  await page.goto(base); await ready();
  const chooseTarget = async(score)=>{
    await page.getByRole('button',{name:'点数を選ぶ',exact:true}).click();
    const bands=[[2,40],[41,80],[81,120],[121,160],[161,180]];
    const [min,max]=bands.find(([a,b])=>score>=a && score<=b);
    await page.locator('#scoreBands').getByRole('button',{name:`${min}〜${max}`,exact:true}).click();
    await page.locator('#scoreChoices').getByRole('button',{name:String(score),exact:true}).click();
    assert.equal(await page.locator('#scorePicker').isVisible(),false);
  };
  assert.ok(!await page.locator('.hero').textContent().then(t=>t.includes('Safari')));

  assert.equal(await page.evaluate(()=>checkoutByScore.size),179);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow');
  assert.equal(await page.locator('.dartBtn').count(),23);
  assert.equal(await page.locator('input[value="sep_double"]').isChecked(),true);
  assert.equal(await page.getByRole('button',{name:'SB',exact:true}).isEnabled(),true);
  await page.locator('#rangePreset').selectOption('121-170');
  for(let i=0;i<15;i++){
   assert.ok(await page.evaluate(()=>startScore>=121 && startScore<=170 && ![159,162,163,165,166,168,169].includes(startScore)));
   await page.getByRole('button',{name:'新しい問題',exact:true}).click();
  }
  await page.locator('#rangeMin').fill('171');await page.locator('#rangeMax').fill('180');
  const prior=await page.locator('#startScore').textContent();
  await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  assert.equal(await page.locator('#startScore').textContent(),prior);
  assert.match(await page.locator('#rangeMessage').textContent(),/上がれる点数/);
  await page.locator('#rangeMin').fill('40');await page.locator('#rangeMax').fill('40');
  await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  assert.equal(await page.locator('#standardAnswer').textContent(),'「回答する」を押すと表示されます');
  await page.getByRole('button',{name:'ダブル',exact:true}).click();
  await page.getByRole('button',{name:'20',exact:true}).click();
  assert.match(await page.locator('#standardAnswer').textContent(),/回答する/);
  await page.getByRole('button',{name:'回答する',exact:true}).click();
  assert.equal(await page.locator('#accuracy').textContent(),'100%');
  assert.equal(await page.locator('#statsCount').textContent(),'1正解 / 1回答');
  assert.equal(await page.getByRole('button',{name:'20',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'1投戻す',exact:true}).click();
  assert.equal(await page.locator('#statsCount').textContent(),'0正解 / 0回答');
  assert.equal(await page.locator('#currentScore').textContent(),'40');
  for(let i=0;i<3;i++)await page.getByRole('button',{name:'MISS',exact:true}).click();
  await page.getByRole('button',{name:'回答する',exact:true}).click();
  assert.equal(await page.locator('#accuracy').textContent(),'0%');
  assert.match(await page.locator('#reviewScores').textContent(),/40/);
  await page.getByRole('button',{name:'新しい問題',exact:true}).click();
  await page.getByRole('button',{name:'20',exact:true}).click();
  if(await page.locator('#submitAnswer').isEnabled()) await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'1正解 / 2回答');
  assert.equal(await page.locator('#reviewScores').textContent(),'復習待ちはありません');
  await page.locator('#customScore').fill('72');await page.locator('#customRoute').fill('T12,D18');
  await page.getByRole('button',{name:'登録',exact:true}).click();
  assert.match(await page.locator('#savedList').textContent(),/T12 → D18/);
  await page.locator('#customScore').fill('9');await page.locator('#customRoute').fill('D1,D4');
  await page.getByRole('button',{name:'登録',exact:true}).click();
  assert.match(await page.locator('#customMessage').textContent(),/合計点/);
  await page.reload();await ready();
  if(await page.locator('#submitAnswer').isEnabled()) await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'1正解 / 2回答');
  assert.equal(await page.locator('#rangeMin').inputValue(),'40');
  assert.match(await page.locator('#savedList').textContent(),/T12 → D18/);
  await page.locator('input[value="fat_master"]').check();
  assert.equal(await page.locator('#statsCount').textContent(),'0正解 / 0回答');
  assert.equal(await page.getByRole('button',{name:'SB',exact:true}).isDisabled(),true);
  await page.locator('#rangeMin').fill('60');await page.locator('#rangeMax').fill('60');
  await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  await page.getByRole('button',{name:'トリプル',exact:true}).click();
  await page.getByRole('button',{name:'20',exact:true}).click();
  assert.match(await page.locator('#standardAnswer').textContent(),/回答する/);
  await page.getByRole('button',{name:'回答する',exact:true}).click();
  assert.equal(await page.locator('#accuracy').textContent(),'100%');
  await page.locator('input[value="sep_double"]').check();
  await page.locator('#rangeMin').fill('170');await page.locator('#rangeMax').fill('170');
  await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  await page.getByRole('button',{name:'20',exact:true}).click();await page.getByRole('button',{name:'20',exact:true}).click();
  await page.getByRole('button',{name:'BULL',exact:true}).click();
  assert.equal(await page.locator('#currentScore').textContent(),'0');
  if(await page.locator('#submitAnswer').isEnabled()) await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'2正解 / 3回答');
  // Preserve the original single-out workflow alongside DO/MO.
  await page.locator('input[value="fat_single"]').check();
  await page.locator('#rangeMin').fill('40');await page.locator('#rangeMax').fill('40');
  await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  await page.getByRole('button',{name:'シングル',exact:true}).click();
  await page.getByRole('button',{name:'20',exact:true}).click();await page.getByRole('button',{name:'20',exact:true}).click();
  await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'1正解 / 1回答');
  await page.locator('input[value="sep_double"]').check();
  await page.locator('#rangeMin').fill('170');await page.locator('#rangeMax').fill('170');
  await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  if(await page.locator('#submitAnswer').isEnabled()) await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'2正解 / 3回答');
  // Offline launch in a new page using the same installed origin and stored state.
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  const cachePaths=await page.evaluate(async()=>{const names=await caches.keys();const cache=await caches.open(names.find(n=>n.endsWith('-v4')));return (await cache.keys()).map(r=>new URL(r.url).pathname);});
  assert.ok(cachePaths.some(p=>p.endsWith('/icons/icon-512.png')));
  await page.close();await context.setOffline(true);page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await ready();
  assert.equal(await page.locator('#rangeMin').inputValue(),'170');
  if(await page.locator('#submitAnswer').isEnabled()) await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'2正解 / 3回答');
  assert.equal(await page.evaluate(()=>checkoutByScore.size),179);
  await page.getByRole('button',{name:'トリプル',exact:true}).click();
  await page.getByRole('button',{name:'20',exact:true}).click();await page.getByRole('button',{name:'20',exact:true}).click();
  await page.getByRole('button',{name:'BULL',exact:true}).click();
  await page.locator('#submitAnswer').click();
  assert.equal(await page.locator('#statsCount').textContent(),'3正解 / 4回答');
  await chooseTarget(169);
  assert.equal(await page.locator('#startScore').textContent(),'169');
  assert.match(await page.locator('#standardAnswer').textContent(),/回答する/);
  await page.getByRole('button',{name:'3本で上がれない',exact:true}).click();
  assert.match(await page.locator('#resultText').textContent(),/正解/);
  assert.match(await page.locator('#standardAnswer').textContent(),/上がれません/);
  await chooseTarget(121);
  await page.getByRole('button',{name:'3本で上がれない',exact:true}).click();
  assert.equal(await page.locator('#resultText').textContent(),'不正解');
  assert.match(await page.locator('#missPlans').textContent(),/S20.*101点/);
  await page.locator('input[value="fat_master"]').check();
  assert.equal(await page.locator('#startScore').textContent(),'121');
  await chooseTarget(2);
  assert.equal(await page.locator('#startScore').textContent(),'2');
  await chooseTarget(180);
  assert.equal(await page.locator('#startScore').textContent(),'180');
  await page.getByRole('button',{name:'トリプル',exact:true}).click();
  await page.locator('#numberGrid').getByRole('button',{name:'20',exact:true}).click();
  assert.equal(await page.locator('#inputStartScore').textContent(),'180');
  assert.equal(await page.locator('#inputCurrentScore').textContent(),'120');
  const box=await page.locator('.liveScore').boundingBox();
  assert.ok(box.y>=0 && box.y+box.height<=844,'live score stays visible during input');
  await page.getByRole('button',{name:'1投戻す',exact:true}).click();
  assert.equal(await page.locator('#inputCurrentScore').textContent(),'180');
  await page.getByRole('button',{name:'点数を選ぶ',exact:true}).click();
  await page.getByRole('button',{name:'閉じる',exact:true}).click();
  assert.equal(await page.locator('#startScore').textContent(),'180');
  assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 }finally{
  if(browser)await browser.close();
  server.kill('SIGTERM');await once(server,'exit');
 }
});
