const {test} = require('node:test');
const assert = require('node:assert/strict');
const {spawn} = require('node:child_process');
const path = require('node:path');
const {once} = require('node:events');
const {chromium, devices} = require('playwright');

test('iPhone-sized PWA: range, rules, reversible stats, custom routes, persistence and offline launch', {timeout:60000}, async()=>{
 const root=path.resolve(__dirname,'..');
 const server=spawn('python3',['-u','-m','http.server','0','--bind','127.0.0.1','--directory',path.dirname(root)],{stdio:['ignore','pipe','ignore']});
 let browser;
 try{
  const [line]=await once(server.stdout,'data');
  const port=String(line).match(/port (\d+)/)[1];
  const base=`http://127.0.0.1:${port}/${path.basename(root)}/`;
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',args:['--no-sandbox']});
  const context=await browser.newContext({...devices['iPhone 13'],defaultBrowserType:undefined});
  let page=await context.newPage();
  const errors=[]; const failed=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400 && !r.url().endsWith('/favicon.ico')) failed.push(r.url());});
  const ready=async()=>page.waitForFunction(()=>document.getElementById('currentScore').textContent!=='--');
  await page.goto(base); await ready();
  const screen = async(name)=>page.locator('#'+name+'Screen').isVisible();
  const fits = async(name)=>{
    const layout=await page.locator('#'+name+'Screen').evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight,bottom:el.getBoundingClientRect().bottom,height:innerHeight}));
    assert.ok(layout.scroll<=layout.client+1,`${name} needs scrolling: ${JSON.stringify(layout)}`);
    assert.ok(layout.bottom<=layout.height,`${name} leaves viewport`);
  };
  const settings = async()=>page.getByRole('button',{name:'設定',exact:true}).click();
  const range = async(min,max,order='random')=>{
    await settings();
    await page.locator('#rangeMin').fill(String(min)); await page.locator('#rangeMax').fill(String(max));
    await page.locator('#questionOrder').selectOption(order);
    await page.getByRole('button',{name:'範囲を適用',exact:true}).click();
  };
  const chooseTarget = async(score)=>{
    await page.getByRole('button',{name:'点数を選ぶ',exact:true}).click();
    const min=score<=20 ? 2 : Math.floor((score-1)/20)*20+1;
    const max=score<=20 ? 20 : min+19;
    await page.locator('#scoreBands').getByRole('button',{name:`${min}〜${max}`,exact:true}).click();
    await page.locator('#scoreChoices').getByRole('button',{name:String(score),exact:true}).click();
    assert.equal(await page.locator('#scorePicker').isVisible(),false);
  };
  const enter=async(prefix,number)=>page.locator(`#dartboardHost [data-token="${prefix}${number}"]`).last().click();
  const outerBull=async()=>{const target=page.locator('[data-outer-bull]');const box=await target.boundingBox();await target.click({position:{x:box.width*.2,y:box.height*.5}});};
  const submit=async()=>page.getByRole('button',{name:'回答する',exact:true}).click();
  const next=async()=>page.getByRole('button',{name:'次の問題',exact:true}).click();
  assert.equal(await page.evaluate(()=>checkoutByScore.size),179);
  assert.equal(await page.locator('.dartBtn').count(),1);
  assert.equal(await page.locator('.appNav button').last().textContent(),'設定');
  assert.equal(await page.locator('#activeModeLabel').textContent(),'ダブルアウト');
  assert.deepEqual(await page.locator('#dartboardHost text').allTextContents(),['20','1','18','4','13','6','10','15','2','17','3','19','7','16','8','11','14','9','12','5']);
  assert.equal(await page.locator('#dartboardHost [data-token="D20"]').count(),1);
  assert.equal(await page.locator('#dartboardHost [data-token="T20"]').count(),1);

  assert.ok(await screen('practice')); await fits('practice');
  for(const size of [{width:375,height:667},{width:320,height:568},{width:390,height:664}]){
    await page.setViewportSize(size);await fits('practice');
    await settings();await fits('settings');
    await page.getByRole('button',{name:'練習',exact:true}).click();
    const button=await page.locator('#submitAnswer').boundingBox();assert.ok(button.y+button.height<=size.height);
  }
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/darts-practice.png'});
  await range(40,40);await enter('D',20);
  assert.equal(await page.locator('.selectedHit').getAttribute('data-token'),'D20');
  assert.equal(await page.locator('.selectedHit').evaluate(el=>getComputedStyle(el).fill),'rgb(250, 204, 21)');
  assert.equal(await page.locator('[data-outer-bull]').getAttribute('r'),'30');

  assert.equal(await page.locator('#statsCount').textContent(),'0正解 / 0回答');
  assert.equal(await page.locator('#standardAnswer').isVisible(),false);
  await submit();assert.ok(await screen('result'));await fits('result');
  await page.setViewportSize({width:320,height:568});await fits('result');await page.setViewportSize({width:390,height:844});
  assert.equal(await page.locator('#statsCount').textContent(),'1正解 / 1回答');
  assert.equal(await page.locator('#resultText').textContent(),'正解');
  assert.equal(await page.locator('#statusBadge').count(),0);
  assert.ok(await page.locator('#resultText').evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=40));
  assert.match(await page.locator('#submittedRoute').textContent(),/D20/);
  await page.getByRole('button',{name:'回答を直す',exact:true}).click();
  assert.ok(await screen('practice'));assert.equal(await page.locator('#statsCount').textContent(),'0正解 / 0回答');
  await enter('S',20);await enter('D',10);await submit();
  assert.equal(await page.locator('#resultText').textContent(),'正解');
  await page.getByRole('button',{name:'回答を直す',exact:true}).click();
  await page.getByRole('button',{name:'クリア',exact:true}).click();
  for(let i=0;i<3;i++)await page.getByRole('button',{name:'MISS',exact:true}).click();
  await submit();assert.match(await page.locator('#reviewScores').textContent(),/1点数/);
  await next();assert.ok(await screen('practice'));await enter('D',20);await submit();
  assert.equal(await page.locator('#statsCount').textContent(),'1正解 / 2回答');
  await page.getByRole('button',{name:'成績',exact:true}).click();await fits('stats');
  assert.match(await page.locator('#mistakeScores').textContent(),/40点.*1回/);
  await page.locator('#mistakeScores button').first().click();assert.equal(await page.locator('#startScore').textContent(),'40');
  await page.getByRole('button',{name:'成績',exact:true}).click();
  await page.setViewportSize({width:320,height:568});await fits('stats');await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'練習',exact:true}).click();assert.ok(await screen('practice'));
  await page.getByRole('button',{name:'成績',exact:true}).click();
  await page.getByRole('button',{name:'自分アレンジ',exact:true}).click();
  await page.locator('#customScore').fill('72');await page.locator('#customRoute').fill('T12,D18');
  await page.getByRole('button',{name:'登録',exact:true}).click();
  assert.match(await page.locator('#savedList').textContent(),/T12 → D18/);await fits('custom');
  await page.setViewportSize({width:320,height:568});await fits('custom');await page.setViewportSize({width:390,height:844});
  await page.locator('#customScore').fill('9');await page.locator('#customRoute').fill('D1,D4');
  await page.getByRole('button',{name:'登録',exact:true}).click();assert.match(await page.locator('#customMessage').textContent(),/合計点/);
  await range(121,170,'sequential');assert.equal(await page.locator('#startScore').textContent(),'121');
  assert.equal(await page.locator('#reviewPriority').isDisabled(),true);
  await page.getByRole('button',{name:'3本で上がれない',exact:true}).click();
  assert.equal(await page.locator('#resultText').textContent(),'不正解');
  const footer=await page.locator('#resultScreen .resultNav button').allTextContents();
  assert.deepEqual(footer,['結果','解説','外した場合','次の問題']);
  await page.getByRole('button',{name:'解説',exact:true}).click();await fits('explanation');
  assert.deepEqual(await page.locator('#explanationScreen .resultNav button').allTextContents(),footer);
  await page.getByRole('button',{name:'外した場合',exact:true}).click();await fits('miss');
  assert.deepEqual(await page.locator('#missScreen .resultNav button').allTextContents(),footer);
  assert.equal(await page.locator('.missItem:visible').count(),4);
  const cards=await page.locator('.missItem:visible').evaluateAll(items=>items.map(el=>el.getBoundingClientRect().x));
  assert.ok(cards.every(x=>Math.abs(x-cards[0])<1),'miss examples use one column');
  assert.match((await page.locator('.missItem:visible').allTextContents()).join(' '),/S20.*101点/);
  await page.setViewportSize({width:320,height:568});await fits('miss');await page.setViewportSize({width:390,height:844});
  await next();assert.equal(await page.locator('#startScore').textContent(),'122');
  await page.getByRole('button',{name:'3本で上がれない',exact:true}).click();await next();
  assert.equal(await page.locator('#startScore').textContent(),'123');
  await range(158,164,'sequential');assert.equal(await page.locator('#startScore').textContent(),'158');
  await page.getByRole('button',{name:'3本で上がれない',exact:true}).click();await next();
  assert.equal(await page.locator('#startScore').textContent(),'160');
  await page.reload();await ready();assert.equal(await page.locator('#questionOrder').inputValue(),'sequential');
  assert.equal(await page.locator('#rangeMin').inputValue(),'158');
  await chooseTarget(169);await page.getByRole('button',{name:'3本で上がれない',exact:true}).click();
  assert.match(await page.locator('#resultText').textContent(),/正解/);await next();
  assert.equal(await page.locator('#startScore').textContent(),'169');
  await settings();await page.locator('#quickMode').selectOption('fat_master');
  await chooseTarget(50);assert.equal(await page.locator('[data-outer-bull]').getAttribute('data-token'),'BULL');
  await outerBull();await submit();assert.match(await page.locator('#resultText').textContent(),/正解/);
  await chooseTarget(60);await enter('T',20);await submit();assert.match(await page.locator('#resultText').textContent(),/正解/);
  await settings();await page.locator('#quickMode').selectOption('fat_single');
  await chooseTarget(40);await enter('S',20);await enter('S',20);await submit();assert.match(await page.locator('#resultText').textContent(),/正解/);
  await settings();await page.locator('#quickMode').selectOption('sep_double');
  await chooseTarget(65);await outerBull();await enter('D',20);await submit();
  assert.match(await page.locator('#resultText').textContent(),/正解/);
  await range(170,170);await enter('T',20);await enter('T',20);await page.getByRole('button',{name:'ブル（50点）',exact:true}).click();await submit();
  assert.match(await page.locator('#resultText').textContent(),/正解/);
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  await page.close();await context.setOffline(true);page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await ready();assert.equal(await page.evaluate(()=>checkoutByScore.size),179);
  await fits('practice');await enter('T',20);await enter('T',20);await page.getByRole('button',{name:'ブル（50点）',exact:true}).click();await submit();
  assert.match(await page.locator('#resultText').textContent(),/正解/);await fits('result');
  await page.evaluate(()=>{progress[currentMode()]=Object.fromEntries(Array.from({length:24},(_,i)=>[i+2,{attempts:1,correct:0,review:true}]));updateStats();});
  await page.getByRole('button',{name:'成績',exact:true}).click();
  await page.setViewportSize({width:320,height:568});await fits('stats');
  assert.equal(await page.locator('#mistakeScores button').count(),9);
  await page.getByRole('button',{name:'次の点数',exact:true}).click();
  assert.match(await page.locator('#mistakeScores button').first().textContent(),/^11点/);
  assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 }finally{
  if(browser)await browser.close();
  server.kill('SIGTERM');await once(server,'exit');
 }
});
